### ISSUE TITLE
検索結果が表示されない

### ISSUE THREAD

**Issue by Comamoca** [Ablaze-MIRAI/freasearcher#5]
HEADをgo buildして出来たバイナリで`/.frasearcher -w "golang"`と実行したところファジーファインダーは起動するものの検索結果の一覧が表示されない。

![image](https://user-images.githubusercontent.com/93137338/180681625-1cda5af5-f8e3-4f39-a35d-ccdd0a6aaab0.png)

環境:
Manjaro 21.2.6 Qonos
go version go1.18.2 linux/amd64

**Comment by code-raisan** [comment]
そういえばWindows環境でもそれなりました
PR出した時はちゃんと動いていたんだが....

**Comment by Comamoca** [comment]
問題はサーバー側のものであり、問題が解決済みの為このissueは閉じさせていただきます。:bow:
